### ISSUE TITLE
Implement ease custom action - SHARE

### ISSUE THREAD

**Issue by juankysoriano** [novoda/simple-chrome-custom-tabs#14]
One of the actions that would be most likely included in a chrome custom tab is the `SHARE` action. Is it worth to help developers to include a facility for it? Probably yes.

**Comment by eduardb** [comment]
I added support for the default share menu item, see this commit: 2b0256c3da8c446736488f39f9c3f6fb93e03fb3 But this is very limited, as is not customizable at all.
My questions now are the following: should the custom share be an action button or a menu item? To what degree should it be customizable? My concern is that having it too customizable will lead to having the same functionality as an action button or a menu item, but under a different name.

**Comment by juankysoriano** [comment]
I think that `withDefaultShareMenuItem() is ok. In the other hand it would be good to add the relative for action, but I am afraid of what would happen if you have something like `withDefaultShareAction` + `withActionButton`. In that case we should have to `throw` a `DeveloperError` which I rather not. I think the middle grain approach is to illustrate how a `share` action can be achieved on the demo app and leave here the facility for the menu item as per your commit.

**Comment by juankysoriano** [comment]
Thank you @eduardb , done here: closing this issue as it is done here: #24
