### ISSUE TITLE
Consider fallback for connectivity issues

### ISSUE THREAD

**Issue by Mecharyry** [novoda/simple-chrome-custom-tabs#19]
It would be super useful to have a fallback for any connectivity issues. An example would be to prevent navigation to chrome custom tabs and keep the user in the app to display a nice message stating they need to check their connectivity.

```java
simpleChromeCustomTabs
                .withFallback(
                        new NavigationFallback() {
                            @Override
                            public void onFallbackNavigateTo(Uri url) {
                                openWebUri(uri);
                            }
                        }
                )
                .withIntentCustomizer(customIntent())
                .navigateTo(uri, activity);
```

```java
        simpleChromeCustomTabs
                .withFallback(
                        new NavigationFallback() {
                            @Override
                            public void onFallbackNavigateTo(Uri url) {
                                openWebUri(uri);
                            }
                        }
                )
                .withConnectivityFallback(new ConnectivityFallback())
                .withIntentCustomizer(customIntent())
                .navigateTo(uri, activity);
```
Do it NAO! :tongue:

**Comment by joetimmins** [comment]
I'm not sure checking connectivity is a responsibility of this library. All we want to do here is have an easy way of styling Chrome when it gets opened. We don't want to also decide whether or not to open it at all!

**Comment by juankysoriano** [comment]
I agree with @joetimmins, it seems a bit out of the scope of the library to handle that scenario which could simply be done by creating an extension of `SimpleChromeCustomTabs` which overrides the key logic that starts the navigation flow.

However, what I think the library is missing is to provide a callback which notifies about potential errors during the navigation. The main use case that this would cover could be something like: 

> Upon website navigation error (http request failed) I want to perform customised action.

Examples of customised actions could be displaying an snackbar, dialog, navigate to activities or for example to an static customised error website. 

There is an issue for doing this, #12 , and is the next thing I would like to bring to the lib.

@Mecharyry do you think we could close this one in favour of the linked issue?

**Comment by Mecharyry** [comment]
Yes, sorry @juankysoriano and @joetimmins I didn't notice this for such a long time!
