### ISSUE TITLE
Add more commands - mayLaunchUrl ...

### ISSUE THREAD

**Issue by friedger** [novoda/simple-chrome-custom-tabs#2]
`CustomTabsService.mayLaunchUrl()` and other commands should be accessible for the advanced user.

**Comment by timrijckaert** [comment]
Is this going to be implemented soon?
Thanks

**Comment by blundell** [comment]
@timrijckaert we're trying to find time :-) otherwise pull requests welcome

**Comment by joetimmins** [comment]
Merged in https://github.com/novoda/simple-chrome-custom-tabs/pull/23

**Comment by juankysoriano** [comment]
Closing as this is included here #23
