### ISSUE TITLE
Snackbar incorrect in samples when Chrome T&C not yet accepted

### ISSUE THREAD

**Issue by friedger** [novoda/simple-chrome-custom-tabs#3]
If the user has not yet accepted the terms and conditions of chrome the snack bar is shown but the url is opened with the fallback navigation.

![simplecct](https://cloud.githubusercontent.com/assets/1449049/11157828/221b000c-8a54-11e5-93a7-ca2d4c339e72.gif)

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
