### ISSUE TITLE
Min SDK 15

### ISSUE THREAD

**Issue by rignaneseleo** [novoda/simple-chrome-custom-tabs#35]
Hi,
I'm trying to implement your library but my app is for > 15 SDK while your library is for > 16 SDK.
I have to use `tools:overrideLibrary="com.novoda.simplechromecustomtabs"` to force usage
Why don't you support all versions?

**Comment by piotrek1543** [comment]
@rignaneseleo I wish you found a right answer. If not, I would say that the base of this wrapper, I mean: Chrome Custom Tabs, requires API 16 by default. 

If you want to support older Android devices, please check: https://stackoverflow.com/questions/33060635/how-to-use-chrome-custom-tabs-below-api-16

I used in my work solution above and it's pretty straight forward :-)

Cheers

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
