### ISSUE TITLE
Does not work if a custom tab is created immediately after making a connection

### ISSUE THREAD

**Issue by Saketme** [novoda/simple-chrome-custom-tabs#36]
So, `SimpleChromeCustomTabs` fails if `navigateTo()` is called called right after `SimpleChromeCustomTabs.getInstance().connectTo(this)`. What is the reason for this?

**Comment by juankysoriano** [comment]
Hello @Saketme 

Can you define `fails`? Do you mean it navigates using the fallback mechanism if available? 

`connectTo` would bind the activity to the services required to make chrome custom tabs work. If you are doing the connection in a thread and the navigation in another there might be a race condition where the service is still not bound at the time the navigation attempt happen.

**Comment by Saketme** [comment]
Ah yes, the fallback immediately gets called. I'm not doing multithreading. You can try this in the sample app too, by placing the `navigateTo()` call right after `connectTo()`.

**Comment by juankysoriano** [comment]
I will take a look, my assumption right now is that by placing one call just after the other means that the service is not bound on the navigation attempt. 

The library will internally check if you have a compatible chrome version installed in your device, and if that's the case will try to open the website using chrome tabs. The check for the chrome version happens internally on `connectTo` and this is happening on a background thread. There might be then a bug where the `navigateTo` doesn't wait for that package check to be completed.

**Comment by juankysoriano** [comment]
Hello @Saketme , the following release is fixing your issue: https://github.com/novoda/simple-chrome-custom-tabs/releases/tag/0.1.5

Thank you for your feedback

**Comment by Saketme** [comment]
Thanks @juankysoriano!
