### ISSUE TITLE
Wrong action value when using androidx

### ISSUE THREAD

**Issue by ouchadam** [novoda/simple-chrome-custom-tabs#44]
Similar issue here https://github.com/openid/AppAuth-Android/issues/395

It seems that the `CustomTabsService.ACTION_CUSTOM_TABS_CONNECTION` value is being wrongly transformed into `androidx.browser.customtabs.action.CustomTabsService` by the android jetify tooling.

This means the library never considers the connection to be connected

We may want to consider hardcoding the correct value

**Comment by AndrazP** [comment]
Hi @ouchadam,
I can confirm, this library stops working after enabling jetify.
That's why I've migrated it to AndroidX and made it compile in latest Android Studio. https://github.com/AndrazP/simple-chrome-custom-tabs/tree/androidx
I can create a PR if you are interested.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
